#!/usr/bin/expect
set space ""
while { $argc } {
 set theArg [lindex $argv end-[expr $argc-1]]
 set leng [string length $theArg]
 for {set i 0} {$i < $leng} {incr i} {
   set char [string range $theArg $i $i]
   if { ! [catch {scan $char %c num} msg]} {
     puts -nonewline [format %s%s $space $num]
     set space " "
   }
 }
 incr argc -1
 puts ""
}
