#!/usr/bin/tclsh

#   +--------------------+
#---| Check command line |---
#   +--------------------+

  if {$argc < 1} {
    puts ""
    puts "USAGE:"
    puts ""
    puts "   [file tail [info script]] <tcl_expression>"
    puts ""
    puts "Examples.."
    puts ""
    puts "   c 1 + \\(5\\*20\\)	or:	c \"1 + (5*20)\""
    puts ""
    exit
  }

#   +---------+
#---| commify |---
#   +---------+

  proc commify {num {sep ,}} {
    while {[regsub {^([-+]?\d+)(\d\d\d)} $num "\\1$sep\\2" num]} {}
    return $num
  }

#   +------+
#---| MAIN |---
#   +------+

  regsub -all , $argv {} tmp_argv
  regsub -all x $tmp_argv * clean_argv
  puts [commify [expr $clean_argv]]

exit


#   +---------------------+
#---| OLD /bin/sh VERSION |-----------------------------------------------------
#   +---------------------+

#!/bin/sh

OK=0

if [ $# -eq 3 ]; then

  X=$1
  OP=$2
  Y=$3
  OK=1

  if [ "$OP" = "x" ]; then
    OP=*
  fi

elif [ $# -eq 1 ]; then

  if echo $1 | egrep "\+" > /dev/null
  then
    X=`echo $1 | cut -d+ -f1`
    OP=+
    Y=`echo $1 | cut -d+ -f2`
    OK=1

  elif echo $1 | egrep "\-" > /dev/null
  then
    X=`echo $1 | cut -d- -f1`
    OP=-
    Y=`echo $1 | cut -d- -f2`
    OK=1

  elif echo $1 | egrep "\*" > /dev/null
  then
    X=`echo $1 | cut -d* -f1`
    OP=*
    Y=`echo $1 | cut -d* -f2`
    OK=1

  elif echo $1 | egrep "x" > /dev/null
  then
    X=`echo $1 | cut -dx -f1`
    OP=*
    Y=`echo $1 | cut -dx -f2`
    OK=1

  elif echo $1 | egrep "\/" > /dev/null
  then
    X=`echo $1 | cut -d/ -f1`
    OP=/
    Y=`echo $1 | cut -d/ -f2`
    OK=1

  else
    echo "WTF, I don't understand your command"
    echo "USAGE: `basename $0` x op y"
    exit
  fi

fi

if [ $OK -eq 0 ]; then
  echo "USAGE: `basename $0` x op y"
  exit
fi

if [ "$OP" = "/" ]; then
  PRECISION=6k
else
  PRECISION=""
fi

RESULT=`echo "${PRECISION} $X ${Y}${OP}p" | dc`
echo "$X $OP $Y = $RESULT"

