#!/bin/bash

egrep -v \
"\
^Arrival-Date:\
|^[ 	][ 	]*..., .* ... 20.. ..:..:.. -0500[ 	]*$\
|^Auto-Submitted:\
|boundary=\
|by [a-z][a-z]*water.acmepacket.com .8.14.4/8.14.4/Submit. id \
|by [a-z][a-z]*water.acmepacket.com .8.14.4/8.14.4. with ESMTP id \
|Content-Transfer-Encoding:[ 	][ 	]*\
|[Cc]ontent-[Tt]ype:[ 	][ 	]*\
|Delivered-To:[ 	][ 	]*\
|Diagnostic-Code:[ 	][ 	]*\
|Final-Recipient:[ 	][ 	]*\
|for <labmonitor@acmepacket.com>;[ 	][ 	]*\
|^[ 	][ 	]*for <root@[a-z][a-z]*water.acmepacket.com>.[ 	][ 	]*..., .* ... 20.. ..:..:.. -0500$\
|^From root@acmepacket.com[ 	][ 	]*\
|^From root@[a-z][a-z]*water.localdomain[ 	][ 	]*\
|^From user@localhost.localdomain[ 	][ 	]*\
|^Last-Attempt-Date:[ 	][ 	]*\
|^Message-Id:[ 	][ 	]*\
|^Received:[ 	][ 	]*by [a-z][a-z]*water.localdomain \
|^Received:[ 	][ 	]*from [a-z][a-z]*water.acmepacket.com \
|^Received-From-MTA:[ 	][ 	]*DNS. \
|^Received:[ 	][ 	]*.from root.localhost.[ 	]*$\
|^Remote-MTA:[ 	][ 	]*DNS. \
|^Reporting-MTA:[ 	][ 	]*dns. \
|^Return-Path:[ 	][ 	]*\
|^X-Cron-Env:[ 	][ 	]*\
|^X-Original-To:[ 	][ 	]*\
|################# SSL Certificate Warning ################\
|Certificate for hostname .[a-z][a-z]*water., in file .or by nickname.:\
|/etc/pki/tls/certs/localhost.crt\
|The certificate needs to be renewed; this can be done\
|using the .genkey. program.\
|Browsers will not be able to correctly connect to this\
|web site using SSL until the certificate is renewed.\
|##########################################################\
|Generated by certwatch.1.\
|^Message-ID:[ 	][ 	]*\
|^User-Agent: Heirloom mailx \
|^MIME-Version: \
|^Content-Type: text/plain; charset=us-ascii\
|^[ 	]*$\
" \
/var/mail/`/usr/bin/id -un` \
| sed 's/^Date: /\n\n====================================================================\nDate:/' \
| sed 's/^\(Subject:[ 	][ 	]*.*\)/\1\n--------------------------------------------------------------------/' \

echo
