#!/bin/bash
if [ $# -lt 1 ]; then
  echo USAGE: `basename $0` number ...
else
  while [ $# -gt 0 ]; do
    NUM=`echo $1 | tr '[:lower:]' '[:upper:]'`
    /usr/bin/dc -e "2o16i${NUM}p"
    shift
  done
fi
