#!/usr/bin/tclsh

foreach inhex_ $argv {
  foreach inhex [split $inhex_ :] {
    if {[string trim $inhex] != ""} {
      set indec [expr 0x$inhex]
      puts -nonewline "$indec "
    }
  }
}

puts ""

