#!/bin/sh

PASSWDLEN=16

#=-
#=- When changing a password, change the following (in this order):
#=-
#=-	1. Win7 (ctrl-alt-del)
#=-	2. Oracle Single Sign On (http://OIM.oraclecorp.com/identity)
#=-	3. VPN (http://OIM.oraclecorp.com/identity)
#=-	4. Beehive (??? NOT SURE HOW ???)
#=-	5. Thunderbird (just wait for it to timeout and ask for a new password?)
#=-	6. Pidgin / Icon > Right-Click > Accounts > Modify
#=-
#=- NOTE: SSO requires the following..
#=-    
#=-    Password must contain at least 2 alphabetic character(s)
#=-    Password must contain at least 1 lowercase letter(s)
#=-    Password must contain at least 1 uppercase letter(s)
#=-    Password must contain at least 1 numeric character(s)
#=-
#=-    Password must be at least 8 character(s) long
#=-    Password must not match or contain user ID
#=-    Password must not be a dictionary word
#=-    Password must not match or contain first name
#=-    Password must not match or contain last name
#=-    Password must not be longer than 255 character(s)
#=-
#=- Also, w7 doesn't allow more than 16 chars (I think)

grep ^#=- "$0" | sed 's/^#=-//'

#---------------------------------------------------------------
# CHARSET 0

SUBSTRLEN_00=3
CHARSET_00="!@#$%^"

SUBSTRLEN_01=3
CHARSET_01="QWERTYASDFG"

SUBSTRLEN_02=2
CHARSET_02="123456"

SUBSTRLEN_03=3
CHARSET_03="67890"

SUBSTRLEN_04=3
CHARSET_04="yuiophjklnm"

SUBSTRLEN_05=2
CHARSET_05="ujmik,ol.p;/['987"

#---------------------------------------------------------------
# CHARSET 1

SUBSTRLEN_10=3
CHARSET_10="QWERTYASDFG"

SUBSTRLEN_11=3
CHARSET_11="!@#$%^"

SUBSTRLEN_12=2
CHARSET_12="123456"

SUBSTRLEN_13=3
CHARSET_13="67890"

SUBSTRLEN_14=3
CHARSET_14="yuiophjklnm"

SUBSTRLEN_15=2
CHARSET_15="ujmik,ol.p;/['987"

#---------------------------------------------------------------
# CHARSET 2

SUBSTRLEN_20=2
CHARSET_20="!@#$%^"

SUBSTRLEN_21=3
CHARSET_21="QWERTYASDFG"

SUBSTRLEN_22=1
CHARSET_22="123456"

SUBSTRLEN_23=1
CHARSET_23="67890"

SUBSTRLEN_24=4
CHARSET_24="yuiophjklnm"

SUBSTRLEN_25=5
CHARSET_25="ujmik,ol.p;/['987"

#---------------------------------------------------------------
# CHARSET 3

SUBSTRLEN_30=4
CHARSET_30="ujmik,ol.p;/['987"

SUBSTRLEN_31=2
CHARSET_31="yuiophjklnm"

SUBSTRLEN_32=2
CHARSET_32="67890"

SUBSTRLEN_33=2
CHARSET_33="123456"

SUBSTRLEN_34=4
CHARSET_34="QWERTYASDFG"

SUBSTRLEN_35=2
CHARSET_35="!@#$%^"

#---------------------------------------------------------------
# CHARSET 4

SUBSTRLEN_40=2
CHARSET_40="123456"

SUBSTRLEN_41=2
CHARSET_41="67890"

SUBSTRLEN_42=4
CHARSET_42="!@#$%^"

SUBSTRLEN_43=2
CHARSET_43="QWERTYASDFG"

SUBSTRLEN_44=2
CHARSET_44="yuiophjklnm"

SUBSTRLEN_45=4
CHARSET_45="ujmik,ol.p;/['987"

#---------------------------------------------------------------
# CHARSET 5

SUBSTRLEN_55=5
CHARSET_55="ujmik,ol.p;/['987"

SUBSTRLEN_54=2
CHARSET_54="yuiophjklnm"

SUBSTRLEN_50=2
CHARSET_50="!@#$%^"

SUBSTRLEN_51=5
CHARSET_51="QWERTYASDFG"

SUBSTRLEN_52=1
CHARSET_52="123456"

SUBSTRLEN_53=1
CHARSET_53="67890"

#---------------------------------------------------------------
# Start the loop

PASSWDS=32
CURR_CHARSET_CHOICE=0

while [ $PASSWDS -gt 0 ]; do

    echo
    echo =========================================================
    echo CURR_CHARSET_CHOICE:$CURR_CHARSET_CHOICE
    echo

    case $CURR_CHARSET_CHOICE in

        0) \

           CHARSET_0=$CHARSET_00
           CHARSET_1=$CHARSET_01
           CHARSET_2=$CHARSET_02
           CHARSET_3=$CHARSET_03
           CHARSET_4=$CHARSET_04
           CHARSET_5=$CHARSET_05

           SUBSTRLEN_0=$SUBSTRLEN_00
           SUBSTRLEN_1=$SUBSTRLEN_01
           SUBSTRLEN_2=$SUBSTRLEN_02
           SUBSTRLEN_3=$SUBSTRLEN_03
           SUBSTRLEN_4=$SUBSTRLEN_04
           SUBSTRLEN_5=$SUBSTRLEN_05

        ;;

        1) \
           CHARSET_0=$CHARSET_10
           CHARSET_1=$CHARSET_11
           CHARSET_2=$CHARSET_12
           CHARSET_3=$CHARSET_13
           CHARSET_4=$CHARSET_14
           CHARSET_5=$CHARSET_15

           SUBSTRLEN_0=$SUBSTRLEN_10
           SUBSTRLEN_1=$SUBSTRLEN_11
           SUBSTRLEN_2=$SUBSTRLEN_12
           SUBSTRLEN_3=$SUBSTRLEN_13
           SUBSTRLEN_4=$SUBSTRLEN_14
           SUBSTRLEN_5=$SUBSTRLEN_15
        ;;

        2) \
           CHARSET_0=$CHARSET_20
           CHARSET_1=$CHARSET_21
           CHARSET_2=$CHARSET_22
           CHARSET_3=$CHARSET_23
           CHARSET_4=$CHARSET_24
           CHARSET_5=$CHARSET_25

           SUBSTRLEN_0=$SUBSTRLEN_20
           SUBSTRLEN_1=$SUBSTRLEN_21
           SUBSTRLEN_2=$SUBSTRLEN_22
           SUBSTRLEN_3=$SUBSTRLEN_23
           SUBSTRLEN_4=$SUBSTRLEN_24
           SUBSTRLEN_5=$SUBSTRLEN_25
        ;;

        3) \
           CHARSET_0=$CHARSET_30
           CHARSET_1=$CHARSET_31
           CHARSET_2=$CHARSET_32
           CHARSET_3=$CHARSET_33
           CHARSET_4=$CHARSET_34
           CHARSET_5=$CHARSET_35

           SUBSTRLEN_0=$SUBSTRLEN_30
           SUBSTRLEN_1=$SUBSTRLEN_31
           SUBSTRLEN_2=$SUBSTRLEN_32
           SUBSTRLEN_3=$SUBSTRLEN_33
           SUBSTRLEN_4=$SUBSTRLEN_34
           SUBSTRLEN_5=$SUBSTRLEN_35
        ;;

        4) \
           CHARSET_0=$CHARSET_40
           CHARSET_1=$CHARSET_41
           CHARSET_2=$CHARSET_42
           CHARSET_3=$CHARSET_43
           CHARSET_4=$CHARSET_44
           CHARSET_5=$CHARSET_45

           SUBSTRLEN_0=$SUBSTRLEN_40
           SUBSTRLEN_1=$SUBSTRLEN_41
           SUBSTRLEN_2=$SUBSTRLEN_42
           SUBSTRLEN_3=$SUBSTRLEN_43
           SUBSTRLEN_4=$SUBSTRLEN_44
           SUBSTRLEN_5=$SUBSTRLEN_45
        ;;

        5) \
           CHARSET_0=$CHARSET_50
           CHARSET_1=$CHARSET_51
           CHARSET_2=$CHARSET_52
           CHARSET_3=$CHARSET_53
           CHARSET_4=$CHARSET_54
           CHARSET_5=$CHARSET_55

           SUBSTRLEN_0=$SUBSTRLEN_50
           SUBSTRLEN_1=$SUBSTRLEN_51
           SUBSTRLEN_2=$SUBSTRLEN_52
           SUBSTRLEN_3=$SUBSTRLEN_53
           SUBSTRLEN_4=$SUBSTRLEN_54
           SUBSTRLEN_5=$SUBSTRLEN_55
        ;;

        *) echo WTF
           exit
        ;;
    esac

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    < /dev/urandom tr -dc $CHARSET_0 | head -c$SUBSTRLEN_0
    < /dev/urandom tr -dc $CHARSET_1 | head -c$SUBSTRLEN_1
    < /dev/urandom tr -dc $CHARSET_2 | head -c$SUBSTRLEN_2
    < /dev/urandom tr -dc $CHARSET_3 | head -c$SUBSTRLEN_3
    < /dev/urandom tr -dc $CHARSET_4 | head -c$SUBSTRLEN_4
    < /dev/urandom tr -dc $CHARSET_5 | head -c$SUBSTRLEN_5
    echo

    PASSWDS=`expr $PASSWDS - 8`
    CURR_CHARSET_CHOICE=`expr $CURR_CHARSET_CHOICE + 1`
    CURR_CHARSET_CHOICE=`expr $CURR_CHARSET_CHOICE % 6`

done

echo ""
