#!/bin/sh

PASSLEN=16

#   +---------------------+
#---| All printable chars |---
#   +---------------------+

doit0 ()
{
  echo "     `cat /dev/urandom | tr -dc [:print:] | head -c $1`"
}

#   +-----------------------------------------+
#---| A little more restrictive character set |---
#   +-----------------------------------------+

doit1 ()
{
  echo "     `cat /dev/urandom | tr -d [:blank:] | tr -dc [:print:] | head -c $1`"
}

#   +--------------------------------+
#---| My customized character set #1 |---
#   +--------------------------------+

doit2 ()
{
  echo "     `cat /dev/urandom |tr -dc \!-/\:-@\[-_\{-\~[:alnum:] | head -c$1`"
}

#   +--------------------------------+
#---| My customized character set #2 |---
#   +--------------------------------+

doit2 ()
{
  echo "     `cat /dev/urandom | tr -dc \!-/\:-@\[-_\{-\~[:alnum:] | tr -d \~\!\@\#\$\%\^\&\*\(\)+-=\{\}\[\]\|\:\;\<\>,. | head -c$1`"
}

#   +--------------------------------+
#---| My customized character set #3 |---
#   +--------------------------------+

doit3 ()
{
  echo "     `cat /dev/urandom | tr -dc [:alnum:] | head -c$1`"
}

#   +------+
#---| MAIN |---
#   +------+

echo ""

I=0 ; while [ $I -lt 16 ]; do
  doit3 $PASSLEN
  I=`expr $I + 1`
done

echo ""
